### ISSUE TITLE
Long response times from the API

### ISSUE THREAD

**Issue by snejus** [tranxuanthang/lrclib#18]
For the past couple of hours `LRCLib` api takes a while to respond, for example:

```sh
$ count 'curl https://lrclib.net/api/search --url-query track_name=Mamontovas -vv'
* Host lrclib.net:443 was resolved.
* IPv6: (none)
* IPv4: 95.216.150.199
*   Trying 95.216.150.199:443...
* Connected to lrclib.net (95.216.150.199) port 443
* ALPN: curl offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: none
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384 / x25519 / id-ecPublicKey
* ALPN: server accepted http/1.1
* Server certificate:
*  subject: CN=lrclib.net
*  start date: Jul 31 22:40:54 2024 GMT
*  expire date: Oct 29 22:40:53 2024 GMT
*  subjectAltName: host "lrclib.net" matched cert's "lrclib.net"
*  issuer: C=US; O=Let's Encrypt; CN=E5
*  SSL certificate verify ok.
*   Certificate level 0: Public key type EC/prime256v1 (256/128 Bits/secBits), signed using ecdsa-with-SHA384
*   Certificate level 1: Public key type EC/secp384r1 (384/192 Bits/secBits), signed using sha256WithRSAEncryption
*   Certificate level 2: Public key type RSA (4096/152 Bits/secBits), signed using sha256WithRSAEncryption
* using HTTP/1.x
> GET /api/search?track_name=Mamontovas HTTP/1.1
> Host: lrclib.net
> User-Agent: curl/8.9.1
> Accept: */*
> 
* Request completely sent off
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
< HTTP/1.1 200 OK
< Server: nginx/1.22.1
< Date: Sun, 08 Sep 2024 17:42:14 GMT
< Content-Type: application/json
< Content-Length: 2
< Connection: keep-alive
< vary: origin, access-control-request-method, access-control-request-headers
< access-control-allow-origin: *
< 
* Connection #0 to host lrclib.net left intact
[]
23s 186ms 276us
```

Is this expected?

**Comment by tranxuanthang** [comment]
This is not expected, normally most requests should be served in under 500ms. It seems lrclib.net is receiving a huge number of search requests recently, but it doesn't appear to be an attack. Maybe this is a sign that the server needs to be scaled up.

**Comment by mgytr** [comment]
Same, takes around 18 seconds for fetching lyrics

**Comment by mgytr** [comment]
Much better now, around 6 seconds on average

**Comment by TheGamer1002** [comment]
I'm seeing a lot of "connection closed before message completed", "operation timed out", and "connection reset by peer" messages in LRCGET, so something's definitely wacky. In fact, every request I've made this morning has failed in one of these three ways.

**Comment by tranxuanthang** [comment]
It seems part of the problem is on Hetzner's side. I think they are short on shared resources for their Intel-based servers, so the CPU performance seems to be heavily throttled.

Anyway, I've just upgraded the server to a more powerful AMD-based plan, so everything should be much better now.

The monthly payment for lrclib.net is now around $15. Hopefully, more people will step up to make monthly sponsorships so that I can comfortably cover the cost.

**Comment by mgytr** [comment]
The wait time is now ~300ms, the issue has been fixed

**Comment by outlawishhh** [comment]
```The operation timed out  (ErrorCode=12002)```
still facing this issue :(

**Comment by mgytr** [comment]
> `The operation timed out (ErrorCode=12002)` still facing this issue :(

works fine for me

**Comment by outlawishhh** [comment]
> > `The operation timed out (ErrorCode=12002)` still facing this issue :(
> 
> works fine for me

yeah nvm i was being dumb (i think i got ratelimited or something😭)
