### ISSUE TITLE
Error initiating the LRCLIB server

### ISSUE THREAD

**Issue by GL-Doses** [tranxuanthang/lrclib#20]
I started to use LRCLIB server two months ago and was always without problem.
But after downloading the lastest Database Dump, the server gave the following error when initiated:

```
thread 'main' panicked at /usr/src/lrclib/server/src/lib.rs:59:32:
Cannot initialize connection to SQLite database!: rusqlite_migrate error: MigrationDefinition(DatabaseTooFarAhead)
Caused by:
    Attempt to migrate a database with a migration number that is too high
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

What can I do to fix it?
Thanks.

**Comment by DataM0del** [comment]
> I started to use LRCLIB server two months ago and was always without problem. But after downloading the lastest Database Dump, the server gave the following error when initiated:
> 
> ```
> thread 'main' panicked at /usr/src/lrclib/server/src/lib.rs:59:32:
> Cannot initialize connection to SQLite database!: rusqlite_migrate error: MigrationDefinition(DatabaseTooFarAhead)
> Caused by:
>     Attempt to migrate a database with a migration number that is too high
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> What can I do to fix it? Thanks.

there's too many things to migrate, at least that's what I think based off of the error. Maybe *don't* migrate it? (I don't know how to do that though)

**Comment by tranxuanthang** [comment]
Hey could you try the latest commit in `main` branch I just pushed? It should fix your issue.

**Comment by GL-Doses** [comment]
I tried the last commit and it really fixed the issue.
Thanks for the quick fix and for your hard working in this amazing project.
