### ISSUE TITLE
Problem searching for specific song

### ISSUE THREAD

**Issue by 7ih** [tranxuanthang/lrclib#23]
For some reason lrclib hates This My Life. 

When you search for all the artists nothing comes up: https://lrclib.net/api/search?artist_name=Lyrical+Lemonade%2C+Lil+Skies%2C+Lil+Tecca%2C+%26+The+Kid+Laroi&track_name=This+My+Life

And when you search "This My Life", you get songs called "This Is My Life": https://lrclib.net/search/this%20my%20life

But the song shows up if you only search a few of the artists: https://lrclib.net/api/search?artist_name=Lil+Skies%2C+Lil+Tecca%2C+%26+The+Kid+Laroi&track_name=This+My+Life

Very specific problem so I understand if this doesn't get fixed for a while (unless you can think of a reason rq)
Thanks

**Comment by tranxuanthang** [comment]
Fixed this in my private branch and deployed to lrclib.net. I will push the changes to `main` when I get home.

**Comment by 7ih** [comment]
Niceee thank you
