### ISSUE TITLE
Cannot submit lyrics due to a request error for `/request-challenge` endpoint

### ISSUE THREAD

**Issue by snejus** [tranxuanthang/lrclib#32]
Been trying to submit lyrics using lrcget and failing to do so due to this error:

![image](https://github.com/user-attachments/assets/a9b31034-1680-4677-b749-5420e0eb5d69)

I also noticed that the API has slowed down. I guess that's due to increased loads?

**Comment by tranxuanthang** [comment]
I'm aware that `/request-challenge` API is slow, as I log every requests that take too long to process on server-side.

I've made some changes, so for now it is a bit more acceptable!

![image](https://github.com/user-attachments/assets/696792f0-dac2-4b2e-bfc6-95317e95c556)
