### ISSUE TITLE
Consider offering a compressed database dump

### ISSUE THREAD

**Issue by JerwuQu** [tranxuanthang/lrclib#9]
Example of zstd compression with default options:

![image](https://github.com/tranxuanthang/lrclib/assets/3710677/93963d50-97bb-4c05-8390-ffc892af7dca)

Sidenote, but creating a torrent file could help with longevity and alleviate hosting as well :)

**Comment by tranxuanthang** [comment]
Thank you for your suggestion. I used to provide compressed data dumps, but the backing up process ran a bit long and caused the lrclib.net server's CPUs to reach 100% usage the entire time. But I'll think of a way.

**Comment by tranxuanthang** [comment]
This is resolved so allow me to close this issue.
